import random 

# Initialize the genres to choose from
action = ["Die Hard", "The Matrix", "Bullet Train", "The terminator", "Top Gun", "Casino Royale"]
comedy = ["Austin Powers", "The Hangover", "Monty Python's Life of Brian", "Pineapple Express", "Smokey and The Bandit"]
romance = ["The Notebook", "Casablanca", "Breakfast at Tiffany's", "Titanic", "In the Mood for Love"]
horror = ["The Exorcist", "The Shining", "A Quiet Place","Halloween", "The Menu"]
drama = ["Poor Things", "Forrest Gump", "The Shawshank Redemption", "The Truman Show", "Killers of the Flower Moon"]
